/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_surfacemark_SurfaceLayer */

#ifndef _Included_com_cidana_testcustomdatasource_SurfaceLayer
#define _Included_com_cidana_testcustomdatasource_SurfaceLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_surfacemark_SurfaceLayer
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cidana_testcustomdatasource_SurfaceLayer_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_app_surfacemark_SurfaceLayer
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cidana_testcustomdatasource_SurfaceLayer_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_app_surfacemark_SurfaceLayer
 * Method:    native_start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cidana_testcustomdatasource_SurfaceLayer_native_1start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_app_surfacemark_SurfaceLayer
 * Method:    native_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cidana_testcustomdatasource_SurfaceLayer_native_1stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
